#!/bin/bash

# normalize mtdbt2f4d kadist 10-year data
# conform to http://meta-the-difference.com/_log.txt
# cp -p preserves file attributes date (mv doesnt work)
# touch -t 202101152350 path/to/filename to correct date modified

# 0. prep dir/* to conform to _log
#    _dates-formatted is ISO for reference
#    _dates is touch-required format
#    assembled by correlating original mod dates
#    from meta-the-difference.com to _log

# 1. iterate through subdirs
#    rm files not appearing in _log.txt
#    touch _files to correct date modified
#    rm extension
#    replace with DATES[]

# 2. cleanup tmp to produce
#    out/eot
#    out/pdf
#    out/png
#    out/ttf
#    out/woff

DATES=()
IFS=$'\n' read -d '' -r -a IN < _dates.txt
for i in ${!IN[@]}; do
    DATES[$i]=${IN[$i]}
done

cp -rp ../in ../tmp
cd ../tmp
for D in */; do 
    cd $D
    pwd 

    rm mtdbt2f4d-.*
    rm mtdbt2f4d-0.*
    rm mtdbt2f4d-60[6-9].*
    rm mtdbt2f4d-61[0-9].*
    rm mtdbt2f4d.*

    read -p "Press return to continue ..."

    for file in mtdbt2f4d-*.*; do
        cp -p -- "$file" "${file%%.*}"
    done

    TYPE=${D%/}     # rm trailing slash
    rm *.$TYPE      # cleanup
    mkdir ../$TYPE-tmp  
    for file in mtdbt2f4d-[0-9]*; do
        cp -p "$file" "$(printf "../$TYPE-tmp/mtdbt2f4d-%05d.$TYPE" "${file#mtdbt2f4d-}")"
    done

    cd ../$TYPE-tmp
    i=0
    for file in mtdbt2f4d-[0-9]*.*; do
        touch -t ${DATES[$i]} $file
        ((i++))
    done

    cd ../
    rm -r $TYPE
    cp -r -p $TYPE-tmp $TYPE
    rm -r $TYPE-tmp
    ls $TYPE/
    echo "** $TYPE done **"
done

cd ../
rm -rf out
cp -rp tmp out
rm -rf tmp
open .
echo "** done **"

exit
