#!/bin/bash

# cleanup *.ttf so that each has correct font-family and font-name (style)
# requires fontforge 2017* like mtdbt2f-compile

# 0. iterate throught ttf, woff
#    out/ttf
#    out/woff

cd ../out/ttf
# add .woff
pwd
read -p "Press return to continue ..."

i=0
for file in mtdbt2f4d-[0-9]*; do
    FONT=${file%.*}     # mtdbt2f-#####
    FAMILY=${FONT%-*}   # mtdbt2f
    WEIGHT=${FONT#*-}   # #####
    TYPE=${file#*.}     # .ttf, .woff
    echo "----------"
    echo $i
    echo "----------"
    echo $FONT
    echo $FAMILY
    echo $WEIGHT
    echo $TYPE

    # SetFontNames() is the fontforge cmd for manipulating names
    # 
    # SetFontNames(fontname[, family[, fullname[, weight[, copyright-notice[, fontversion]]]]])

    /Applications/FontForge.app/Contents/Resources/opt/local/bin/fontforge -lang=ff -c 'Open($1); \
        SetFontNames($3,$3,$3,$5,$6,$7); \
        Generate($2)' $FONT.$TYPE $FONT.$TYPE $FONT $FAMILY $WEIGHT 2>> log.txt
    ((i++))
done
ls

echo "** done **"
exit
