#!/bin/bash

# generate composite img with dates 
# using conformed data from /out/png

rm _comp.png
rm _dates.txt
echo " "
echo "------"
echo " "

# 0. collect date modified for *.png
#    using identify -format '%[date:modify]\n'
#    _dates.txt -- corrected modified dates

for i in ../out/png/*.png; do 
    identify -format '%[date:modify]\n' "$i" >> _dates.txt; 
done
cat _dates.txt

# 1. create imagemagick montage
#    using miff imagemagick multiimage format
#    to annotate individual img with _dates.txt
#    writes onto image but provides more control

DATES=()
IFS=$'\n' read -d '' -r -a IN < _dates.txt
for i in ${!IN[@]}; do
    DATES[$i]=${IN[$i]}
done

i=0
for f in ../out/png/*.png; do
    convert "$f" -resize 300x300 -gravity northwest \
    -annotate +0+0 "${DATES[$i]}" miff:-
    ((i++))
done | montage -geometry 400x200+4+2 -tile 14x - _comp.png

open _comp.png

exit
